### ISSUE TITLE
usage of reqwest rustls-tls-webpki-roots

### ISSUE THREAD

**Issue by alexanderkjall** [EmbarkStudios/tame-index#25]
**Is your feature request related to a problem? Please describe.**

I'm looking at packaging this for Debian, and noticed the usage of `reqwest/rustls-tls-webpki-roots`, this collides with our packaging policies as it duplicates the ca-certs into the binary, so that the binary have to be rebuilt if there is an update to the ca-certs.

**Describe the solution you'd like**

Use `reqwest/rustls-tls-native-roots` instead.

**Describe alternatives you've considered**

I can just patch the crate to use `reqwest/rustls-tls-native-roots` myself, but I thought that I should also bring this up here, in order to keep the diff between

**Additional context**

Technically this should maybe be a security issue, since it will be a security problem if a ca-cert gets compromised and the binary isn't rebuilt. But since it's so theoretical and other debate about the usage of webpki-roots is public I don't think there is a need to keep this secret.

Also see this comment for an analysis of the situation: https://github.com/rust-lang/rustup/issues/3400#issuecomment-1683762630

**Comment by Jake-Shadle** [comment]
Disable default features and enable [`native-certs`](https://github.com/EmbarkStudios/tame-index/blob/f10814bfc5bb005d1d471edbc24bc96388319c52/Cargo.toml#L24)
