### ISSUE TITLE
Updating gix from 0.52 to 0.53.1 brings breaking changes 

### ISSUE THREAD

**Issue by hds** [EmbarkStudios/tame-index#28]
**Describe the bug**
There is a breaking API change in `gix` 0.53 (compared to 0.52). This update was made in a patch change to `tame-index` (0.5.5 to 0.5.6).

Since this API is exposed in `tame-index`'s public API, it should (in my opinion) require an update to 0.6.

The real world consequences of this is that `cargo-audit` is currently failing to build.

`cargo-audit` specified `rustsec` 0.28.0 which pulls in 0.28.1.
`rustsec` specifies `tame-index` 0.5.5 which pulls in 0.5.6 when building (which is semver appropriate).

The API break in `gix` breaks this. `cargo-audit` could definitely define a `Cargo.lock` file which I think would fix the problem.

However I would still say that the API break in `tame-index` (as it reexports the `gix API) is still a valid issue.

**To Reproduce**
Right now building cargo-audit fails.
```sh
cargo install cargo-audit
```

```
error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /home/stainsby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.28.1/src/repository/git/commit.rs:150:35
    |
150 |         let opts = gix::worktree::state::checkout::Options {
    |                                   ^^^^^ could not find `state` in `worktree`

error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /home/stainsby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.28.1/src/repository/git/commit.rs:156:24
    |
156 |         gix::worktree::state::checkout(
    |                        ^^^^^ could not find `state` in `worktree`

error[E0599]: no method named `fetch_then_checkout` found for struct `tame_index::external::gix::clone::PrepareFetch` in the current scope
   --> /home/stainsby/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.28.1/src/repository/git/repository.rs:169:22
    |
162 |                   let (mut prep_checkout, out) = gix::prepare_clone(url, path)
    |  ________________________________________________-
163 | |                     .map_err(|err| {
164 | |                         format_err!(ErrorKind::Repo, "failed to prepare clone: {}", err)
165 | |                     })?
...   |
168 | |                     .configure_remote(|remote| Ok(remote.with_refspecs([REF_SPEC], DIR)?))
169 | |                     .fetch_then_checkout(&mut progress, should_interrupt)
    | |                     -^^^^^^^^^^^^^^^^^^^ method not found in `PrepareFetch`
    | |_____________________|
    | 
```

This is caused by the `gix` breaking API change here:
https://github.com/Byron/gitoxide/commit/92dd18154b526b4c5132d770960a36ccf739dec8#diff-9a7985575e682d7b38b503ce69b353555b34f1babb1b7a7d8c0ab6eb4c4bb989R7

**Expected behavior**
This shouldn't have happened as `cargo-audit` shouldn't get a breaking API change via the `tame-index` patch update.

**Additional context**
I know that this is a weird Issue report and understand if you're not really interested in fixing this when you're very much in the middle.

However I thought it was worth reporting anyway.

Finally, thanks for your contributions to the ecosystem! It's clear that this crate (which I haven't used myself) is underpinning some important stuff.

**Comment by Jake-Shadle** [comment]
Version 0.5.6 was yanked, and republished as 0.6.0

**Comment by hds** [comment]
> Version 0.5.6 was yanked, and republished as 0.6.0

Thanks for the quick response! It's working correctly for me locally now.

**Comment by Shnatsel** [comment]
It is indeed required by semver to bump major version of `tame-index` every time there is a major version bump of `gix`.

FWIW I anticipated that both `gix` and `tame-index` will bump major semver version frequently (since `tame-index` exposes a lot of `gix` types through the API) and made sure that it does not necessitate major semver bumps in `rustsec`: https://github.com/rustsec/rustsec/pull/961
