### ISSUE TITLE
`gix` upgrades are semver-breaking

### ISSUE THREAD

**Issue by Shnatsel** [EmbarkStudios/tame-index#55]
**Describe the bug**

`cargo audit` fails to build with tame-index 0.9.8 or 0.9.9, breaking CI worldwide: https://github.com/rustsec/rustsec/issues/1142

I've hotfixed the 0.9.8 breakage by upgrading gix in cargo-audit and publishing a new version, but now tame-index 0.9.9 broke it again.

With `gix` structures exposed in the public API, any semver-breaking change in the gix version (even just a semver-incompatible version number with no changes to the actual structures) is an API break for `tame-index` too. It's always a semver break regardless of the specifics of the uses of the API.

Please yank 0.9.9 and re-release it as 0.10.0

**Comment by Jake-Shadle** [comment]
Sorry about that, yanked and rereleased. Going to stop upgrading gix frequently since it usually doesn't provide value.

**Comment by Shnatsel** [comment]
And thank you for the quick fix!

**Comment by Byron** [comment]
> Sorry about that, yanked and rereleased. Going to stop upgrading gix frequently since it usually doesn't provide value.

I agree - since `tame-index` can already do everything it needs to do, there usually isn't much value in updating `gix` to the latest version unless there are relevant fixes or features, which should be evident from the`gix` changelog then.
